version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t dockerrepo .
      - docker tag dockerrepo:latest 982895218397.dkr.ecr.ap-south-1.amazonaws.com/dockerrepo:latest      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 982895218397.dkr.ecr.ap-south-1.amazonaws.com/dockerrepo:latest